package com.uabc.proyecto.themeswitcher
import androidx.compose.ui.graphics.Color

val independence_primaryLight = Color(0xFF00492F)
val independence_onPrimaryLight = Color(0xFFFFFFFF)
val independence_primaryContainerLight = Color(0xFF006341)
val independence_onPrimaryContainerLight = Color(0xFF8CDCB1)

val independence_secondaryLight = Color(0xFF5D5F5F)
val independence_onSecondaryLight = Color(0xFFFFFFFF)
val independence_secondaryContainerLight = Color(0xFFFFFFFF)
val independence_onSecondaryContainerLight = Color(0xFF747676)

val independence_tertiaryLight = Color(0xFF9E001F)
val independence_onTertiaryLight = Color(0xFFFFFFFF)
val independence_tertiaryContainerLight = Color(0xFFB9364D)
val independence_onTertiaryContainerLight = Color(0xFFE5D5D3)

val independence_errorLight = Color(0xFFB78904)
val independence_onErrorLight = Color(0xFFFFFFFF)
val independence_errorContainerLight = Color(0xFFFBC02D)
val independence_onErrorContainerLight = Color(0xFF6C5000)

val independence_backgroundLight = Color(0xFF9EEACD)
val independence_onBackgroundLight = Color(0xFF00150C)
val independence_surfaceLight = Color(0xFF9EEACD)
val independence_onSurfaceLight = Color(0xFF00150C)

val independence_surfaceVariantLight = Color(0xFFDAE5DC)
val independence_onSurfaceVariantLight = Color(0xFF3F4942)
val independence_outlineLight = Color(0xFF6F7A72)
val independence_outlineVariantLight = Color(0xFFBEC9C0)
val independence_scrimLight = Color(0xFF000000)
val independence_inverseSurfaceLight = Color(0xFF2D312E)
val independence_inverseOnSurfaceLight = Color(0xFFEEF2EC)
val independence_inversePrimaryLight = Color(0xFF86D7AC)
val independence_surfaceDimLight = Color(0xFFD7DBD6)
val independence_surfaceBrightLight = Color(0xFFF7FAF5)
val independence_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val independence_surfaceContainerLowLight = Color(0xFFF1F5EF)
val independence_surfaceContainerLight = Color(0xFFEBEFEA)
val independence_surfaceContainerHighLight = Color(0xFFE5E9E4)
val independence_surfaceContainerHighestLight = Color(0xFFE0E3DE)

val independence_primaryDark = Color(0xFF86D7AC)
val independence_onPrimaryDark = Color(0xFF003823)
val independence_primaryContainerDark = Color(0xFF006341)
val independence_onPrimaryContainerDark = Color(0xFF8CDCB1)

val independence_secondaryDark = Color(0xFFFFFFFF)
val independence_onSecondaryDark = Color(0xFF2F3131)
val independence_secondaryContainerDark = Color(0xFFE2E2E2)
val independence_onSecondaryContainerDark = Color(0xFF636565)

val independence_tertiaryDark = Color(0xFFFFB3B1)
val independence_onTertiaryDark = Color(0xFF680011)
val independence_tertiaryContainerDark = Color(0xFFA2142B)
val independence_onTertiaryContainerDark = Color(0xFFFFDAD8)

val independence_errorDark = Color(0xFFFFE2AA)
val independence_onErrorDark = Color(0xFF402D00)
val independence_errorContainerDark = Color(0xFFFBC02D)
val independence_onErrorContainerDark = Color(0xFF6C5000)

val independence_backgroundDark = Color(0xFF22332A)
val independence_onBackgroundDark = Color(0xFFA9F1D4)
val independence_surfaceDark = Color(0xFF22332A)
val independence_onSurfaceDark = Color(0xFFA9F1D4)

val independence_surfaceVariantDark = Color(0xFF2B3A2E)
val independence_onSurfaceVariantDark = Color(0xFFBEC9C0)
val independence_outlineDark = Color(0xFF89938B)
val independence_outlineVariantDark = Color(0xFF3F4942)
val independence_scrimDark = Color(0xFF000000)
val independence_inverseSurfaceDark = Color(0xFFE0E3DE)
val independence_inverseOnSurfaceDark = Color(0xFF2D312E)
val independence_inversePrimaryDark = Color(0xFF136C49)
val independence_surfaceDimDark = Color(0xFF101412)
val independence_surfaceBrightDark = Color(0xFF363A37)
val independence_surfaceContainerLowestDark = Color(0xFF0B0F0C)
val independence_surfaceContainerLowDark = Color(0xFF181D1A)
val independence_surfaceContainerDark = Color(0xFF1C211E)
val independence_surfaceContainerHighDark = Color(0xFF272B28)
val independence_surfaceContainerHighestDark = Color(0xFF313632)
