package com.uabc.proyecto.themeswitcher
import androidx.compose.ui.graphics.Color

val valentine_primaryLight = Color(0xFFA20045)
val valentine_onPrimaryLight = Color(0xFFFFFFFF)
val valentine_primaryContainerLight = Color(0xFFC5255C)
val valentine_onPrimaryContainerLight = Color(0xFFFFE2E6)
val valentine_secondaryLight = Color(0xFF7F525A)
val valentine_onSecondaryLight = Color(0xFFFFFFFF)
val valentine_secondaryContainerLight = Color(0xFFEEB5BE)
val valentine_onSecondaryContainerLight = Color(0xFF6F454C)
val valentine_tertiaryLight = Color(0xFF8A5100)
val valentine_onTertiaryLight = Color(0xFFFFFFFF)
val valentine_tertiaryContainerLight = Color(0xFFDE8C2B)
val valentine_onTertiaryContainerLight = Color(0xFF512D00)
val valentine_errorLight = Color(0xFFA13262)
val valentine_onErrorLight = Color(0xFFFFFFFF)
val valentine_errorContainerLight = Color(0xFFC04B7B)
val valentine_onErrorContainerLight = Color(0xFFFFFBFF)

val valentine_backgroundLight = Color(0xFFFF9EC3)
val valentine_onBackgroundLight = Color(0xFF730A37)

val valentine_surfaceLight = Color(0xFFFF9EC3)
val valentine_onSurfaceLight = Color(0xFF730A37)

val valentine_surfaceVariantLight = Color(0xFFFEDADF)
val valentine_onSurfaceVariantLight = Color(0xFF594045)
val valentine_outlineLight = Color(0xFF8D7074)
val valentine_outlineVariantLight = Color(0xFFE0BEC3)
val valentine_scrimLight = Color(0xFF000000)
val valentine_inverseSurfaceLight = Color(0xFF3C2C2F)
val valentine_inverseOnSurfaceLight = Color(0xFFFFECEE)
val valentine_inversePrimaryLight = Color(0xFFFFB1C0)
val valentine_surfaceDimLight = Color(0xFFEED4D7)
val valentine_surfaceBrightLight = Color(0xFFFFF8F7)
val valentine_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val valentine_surfaceContainerLowLight = Color(0xFFFFF0F1)
val valentine_surfaceContainerLight = Color(0xFFFFE9EB)
val valentine_surfaceContainerHighLight = Color(0xFFFCE2E5)
val valentine_surfaceContainerHighestLight = Color(0xFFF6DCDF)

val valentine_primaryDark = Color(0xFFFFB1C0)
val valentine_onPrimaryDark = Color(0xFF660029)
val valentine_primaryContainerDark = Color(0xFFC5255C)
val valentine_onPrimaryContainerDark = Color(0xFFFFE2E6)
val valentine_secondaryDark = Color(0xFFFFD5DB)
val valentine_onSecondaryDark = Color(0xFF4A252D)
val valentine_secondaryContainerDark = Color(0xFFEEB5BE)
val valentine_onSecondaryContainerDark = Color(0xFF6F454C)
val valentine_tertiaryDark = Color(0xFFFFB86F)
val valentine_onTertiaryDark = Color(0xFF4A2800)
val valentine_tertiaryContainerDark = Color(0xFFDE8C2B)
val valentine_onTertiaryContainerDark = Color(0xFF512D00)
val valentine_errorDark = Color(0xFFFFB0CA)
val valentine_onErrorDark = Color(0xFF640035)
val valentine_errorContainerDark = Color(0xFFE36697)
val valentine_onErrorContainerDark = Color(0xFF54002C)

val valentine_backgroundDark = Color(0xFF672039)
val valentine_onBackgroundDark = Color(0xFFE597B1)

val valentine_surfaceDark = Color(0xFF672039)
val valentine_onSurfaceDark = Color(0xFFE597B1)

val valentine_surfaceVariantDark = Color(0xFF594045)
val valentine_onSurfaceVariantDark = Color(0xFFE0BEC3)
val valentine_outlineDark = Color(0xFFA8898E)
val valentine_outlineVariantDark = Color(0xFF594045)
val valentine_scrimDark = Color(0xFF000000)
val valentine_inverseSurfaceDark = Color(0xFFF6DCDF)
val valentine_inverseOnSurfaceDark = Color(0xFF3C2C2F)
val valentine_inversePrimaryDark = Color(0xFFB71752)
val valentine_surfaceDimDark = Color(0xFF1D1012)
val valentine_surfaceBrightDark = Color(0xFF463538)
val valentine_surfaceContainerLowestDark = Color(0xFF170B0D)
val valentine_surfaceContainerLowDark = Color(0xFF26181A)
val valentine_surfaceContainerDark = Color(0xFF2A1C1E)
val valentine_surfaceContainerHighDark = Color(0xFF352629)
val valentine_surfaceContainerHighestDark = Color(0xFF413033)
